name: lego_app
description: Main shell application.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  injectable: ^2.5.0
  lego_navigation:
    path: ../lego_navigation
  lego_list:
    path: ../../feature/lego_list
  design_system:
    path: ../../core/design_system

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  injectable_generator: ^2.6.1