name: lego_single
description: Lego single feature module.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  injectable: ^2.5.0
  flow_builder: ^0.0.9
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  bdd_widget_test: ^1.8.2

dev_dependencies:
  build_runner: ^2.4.7
  injectable_generator: ^2.6.1
  freezed: ^2.4.5
  dart_style: ^3.0.0  # Required by bdd_widget_test
