name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout repo
        uses: actions/checkout@v3

      - name: 🧰 Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4' # match your Flutter version

      - name: 📦 Install Melos and dependencies
        run: |
          dart pub global activate melos
          melos bootstrap

      - name: ✅ Run Tests
        run: melos exec --dir-exists=test -- flutter test
